/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignupIndexRouteImport } from './routes/signup/index'
import { Route as RestrictedIndexRouteImport } from './routes/restricted/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as GamesIndexRouteImport } from './routes/games/index'
import { Route as ProfileIdRouteImport } from './routes/profile/$id'
import { Route as GamesIdRouteImport } from './routes/games/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestrictedIndexRoute = RestrictedIndexRouteImport.update({
  id: '/restricted/',
  path: '/restricted/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIdRoute = ProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIdRoute = GamesIdRouteImport.update({
  id: '/games/$id',
  path: '/games/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/games/$id': typeof GamesIdRoute
  '/profile/$id': typeof ProfileIdRoute
  '/games/': typeof GamesIndexRoute
  '/login/': typeof LoginIndexRoute
  '/restricted/': typeof RestrictedIndexRoute
  '/signup/': typeof SignupIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/games/$id': typeof GamesIdRoute
  '/profile/$id': typeof ProfileIdRoute
  '/games': typeof GamesIndexRoute
  '/login': typeof LoginIndexRoute
  '/restricted': typeof RestrictedIndexRoute
  '/signup': typeof SignupIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/games/$id': typeof GamesIdRoute
  '/profile/$id': typeof ProfileIdRoute
  '/games/': typeof GamesIndexRoute
  '/login/': typeof LoginIndexRoute
  '/restricted/': typeof RestrictedIndexRoute
  '/signup/': typeof SignupIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/games/$id'
    | '/profile/$id'
    | '/games/'
    | '/login/'
    | '/restricted/'
    | '/signup/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/games/$id'
    | '/profile/$id'
    | '/games'
    | '/login'
    | '/restricted'
    | '/signup'
  id:
    | '__root__'
    | '/'
    | '/games/$id'
    | '/profile/$id'
    | '/games/'
    | '/login/'
    | '/restricted/'
    | '/signup/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GamesIdRoute: typeof GamesIdRoute
  ProfileIdRoute: typeof ProfileIdRoute
  GamesIndexRoute: typeof GamesIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  RestrictedIndexRoute: typeof RestrictedIndexRoute
  SignupIndexRoute: typeof SignupIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/': {
      id: '/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restricted/': {
      id: '/restricted/'
      path: '/restricted'
      fullPath: '/restricted/'
      preLoaderRoute: typeof RestrictedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$id': {
      id: '/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof ProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$id': {
      id: '/games/$id'
      path: '/games/$id'
      fullPath: '/games/$id'
      preLoaderRoute: typeof GamesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GamesIdRoute: GamesIdRoute,
  ProfileIdRoute: ProfileIdRoute,
  GamesIndexRoute: GamesIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  RestrictedIndexRoute: RestrictedIndexRoute,
  SignupIndexRoute: SignupIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
