/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignupIndexRouteImport } from './routes/signup/index'
import { Route as RestrictedIndexRouteImport } from './routes/restricted/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as ListsIndexRouteImport } from './routes/lists/index'
import { Route as GamesIndexRouteImport } from './routes/games/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProfileIdRouteImport } from './routes/profile/$id'
import { Route as ListsListIdRouteImport } from './routes/lists/$listId'
import { Route as GamesIdRouteImport } from './routes/games/$id'
import { Route as ProfileIdIndexRouteImport } from './routes/profile/$id/index'
import { Route as ProfileIdListsListIdRouteImport } from './routes/profile/$id/lists/$listId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestrictedIndexRoute = RestrictedIndexRouteImport.update({
  id: '/restricted/',
  path: '/restricted/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsIndexRoute = ListsIndexRouteImport.update({
  id: '/lists/',
  path: '/lists/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIdRoute = ProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsListIdRoute = ListsListIdRouteImport.update({
  id: '/lists/$listId',
  path: '/lists/$listId',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIdRoute = GamesIdRouteImport.update({
  id: '/games/$id',
  path: '/games/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIdIndexRoute = ProfileIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileIdRoute,
} as any)
const ProfileIdListsListIdRoute = ProfileIdListsListIdRouteImport.update({
  id: '/lists/$listId',
  path: '/lists/$listId',
  getParentRoute: () => ProfileIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/games/$id': typeof GamesIdRoute
  '/lists/$listId': typeof ListsListIdRoute
  '/profile/$id': typeof ProfileIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/games/': typeof GamesIndexRoute
  '/lists/': typeof ListsIndexRoute
  '/login/': typeof LoginIndexRoute
  '/restricted/': typeof RestrictedIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/profile/$id/': typeof ProfileIdIndexRoute
  '/profile/$id/lists/$listId': typeof ProfileIdListsListIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/games/$id': typeof GamesIdRoute
  '/lists/$listId': typeof ListsListIdRoute
  '/admin': typeof AdminIndexRoute
  '/games': typeof GamesIndexRoute
  '/lists': typeof ListsIndexRoute
  '/login': typeof LoginIndexRoute
  '/restricted': typeof RestrictedIndexRoute
  '/signup': typeof SignupIndexRoute
  '/profile/$id': typeof ProfileIdIndexRoute
  '/profile/$id/lists/$listId': typeof ProfileIdListsListIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/games/$id': typeof GamesIdRoute
  '/lists/$listId': typeof ListsListIdRoute
  '/profile/$id': typeof ProfileIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/games/': typeof GamesIndexRoute
  '/lists/': typeof ListsIndexRoute
  '/login/': typeof LoginIndexRoute
  '/restricted/': typeof RestrictedIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/profile/$id/': typeof ProfileIdIndexRoute
  '/profile/$id/lists/$listId': typeof ProfileIdListsListIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/games/$id'
    | '/lists/$listId'
    | '/profile/$id'
    | '/admin/'
    | '/games/'
    | '/lists/'
    | '/login/'
    | '/restricted/'
    | '/signup/'
    | '/profile/$id/'
    | '/profile/$id/lists/$listId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/games/$id'
    | '/lists/$listId'
    | '/admin'
    | '/games'
    | '/lists'
    | '/login'
    | '/restricted'
    | '/signup'
    | '/profile/$id'
    | '/profile/$id/lists/$listId'
  id:
    | '__root__'
    | '/'
    | '/games/$id'
    | '/lists/$listId'
    | '/profile/$id'
    | '/admin/'
    | '/games/'
    | '/lists/'
    | '/login/'
    | '/restricted/'
    | '/signup/'
    | '/profile/$id/'
    | '/profile/$id/lists/$listId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GamesIdRoute: typeof GamesIdRoute
  ListsListIdRoute: typeof ListsListIdRoute
  ProfileIdRoute: typeof ProfileIdRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  GamesIndexRoute: typeof GamesIndexRoute
  ListsIndexRoute: typeof ListsIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  RestrictedIndexRoute: typeof RestrictedIndexRoute
  SignupIndexRoute: typeof SignupIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/': {
      id: '/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restricted/': {
      id: '/restricted/'
      path: '/restricted'
      fullPath: '/restricted/'
      preLoaderRoute: typeof RestrictedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists/': {
      id: '/lists/'
      path: '/lists'
      fullPath: '/lists/'
      preLoaderRoute: typeof ListsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$id': {
      id: '/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof ProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists/$listId': {
      id: '/lists/$listId'
      path: '/lists/$listId'
      fullPath: '/lists/$listId'
      preLoaderRoute: typeof ListsListIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$id': {
      id: '/games/$id'
      path: '/games/$id'
      fullPath: '/games/$id'
      preLoaderRoute: typeof GamesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$id/': {
      id: '/profile/$id/'
      path: '/'
      fullPath: '/profile/$id/'
      preLoaderRoute: typeof ProfileIdIndexRouteImport
      parentRoute: typeof ProfileIdRoute
    }
    '/profile/$id/lists/$listId': {
      id: '/profile/$id/lists/$listId'
      path: '/lists/$listId'
      fullPath: '/profile/$id/lists/$listId'
      preLoaderRoute: typeof ProfileIdListsListIdRouteImport
      parentRoute: typeof ProfileIdRoute
    }
  }
}

interface ProfileIdRouteChildren {
  ProfileIdIndexRoute: typeof ProfileIdIndexRoute
  ProfileIdListsListIdRoute: typeof ProfileIdListsListIdRoute
}

const ProfileIdRouteChildren: ProfileIdRouteChildren = {
  ProfileIdIndexRoute: ProfileIdIndexRoute,
  ProfileIdListsListIdRoute: ProfileIdListsListIdRoute,
}

const ProfileIdRouteWithChildren = ProfileIdRoute._addFileChildren(
  ProfileIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GamesIdRoute: GamesIdRoute,
  ListsListIdRoute: ListsListIdRoute,
  ProfileIdRoute: ProfileIdRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  GamesIndexRoute: GamesIndexRoute,
  ListsIndexRoute: ListsIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  RestrictedIndexRoute: RestrictedIndexRoute,
  SignupIndexRoute: SignupIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
